# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0001_initial'),
        ('bookReviews', '0002_review_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='review_author', to='logreg.UserDB'),
            preserve_default=False,
        ),
    ]
