# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookReviews', '0003_review_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reviewed', to='bookReviews.Book'),
        ),
    ]
