# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookReviews', '0004_auto_20170601_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_id',
        ),
        migrations.AddField(
            model_name='book',
            name='author_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='book_author', to='bookReviews.Author'),
            preserve_default=False,
        ),
    ]
